# 应用名称
spring:
  application:
    name: cages-spring-boot
# 应用服务 WEB 访问端口
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: defaultDataSource
# 数据库连接地址
    url: jdbc:mysql://81.68.230.143:3306/cages?serverTimezone=UTC
# 数据库用户名&密码：
    username: root
    password: hn123456Aa.

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.bobasyu.cagesspringboot.entity

server:
  port: 8000
